[package]
name = "rock-paper-scissors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
platform-dirs = "0.3.0"

[profile.release]
lto = true